trigger:
- main

pool: Tolga-ios

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'FitAI-iOS'
    configuration: 'ProductionRelease'
    xcWorkspacePath: 'iOS-FitAI/iOS-FitAI.xcodeproj'
    sdk: 'iphonesimulator'
    buildArguments: '-derivedDataPath Build/'
    args: '-destination "platform=iOS Simulator,name=iPhone Prod iOS17" -derivedDataPath Build/ CODE_SIGNING_ALLOWED=NO'